version: '3.8'
services:
  mariadb:
    build: .
    container_name: event-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eventdb
      MYSQL_USER: eventuser
      MYSQL_PASSWORD: eventpass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: event-rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=eventuser
      - RABBITMQ_DEFAULT_PASS=eventpass
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mariadb_data:
  rabbitmq_data: 